resource.AddFile("sound/slow.wav")
resource.AddFile("materials/entities/weapon_doorbuster.vtf")
resource.AddFile("materials/entities/weapon_doorbuster.vmt")
resource.AddFile("materials/entities/weapon_doorbuster_ttt.vtf")
resource.AddFile("materials/entities/weapon_doorbuster_ttt.vmt")